version: "3"

services:
    nginx:
        image: nginx:1.14-alpine
        restart: always
        ports:
            - 81:80
        volumes:
            - ./src:/var/www/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        build: ./docker/php
        #image: php:7.2-fpm-alpine
        restart: always
        volumes:
            - ./src:/var/www/
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
        working_dir: /var/www/


    mysql:
        image: mysql:5.7
        restart: always
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=web
            - MYSQL_USER=web
            - MYSQL_PASSWORD=pass
        volumes:
            - ./docker/volumes/mysql:/var/lib/mysql


    pgsql:
        image: postgres
        restart: always
        ports:
            - 5432:5482
        environment:
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: web
            POSTGRES_USER: web
        volumes:
            - ./docker/volumes/pgsql:/var/lib/postgresql/data


#----  Database management ----#
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

#---- Email testing tool ----#
    # mailhog:
    #     image: mailhog/mailhog:v1.0.0
    #     restart: always
    #     ports:
    #         - 8025:8025