version: "3"

services:
    nginx:
        image: nginx:1.14-alpine
        ports:
            - 81:80
        volumes:
            - ./src:/var/www/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php:
        build: ./docker/php
        #image: php:7.2-fpm-alpine
        volumes:
            - ./src:/var/www/
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
        working_dir: /var/www/

    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=web
            - MYSQL_USER=web
            - MYSQL_PASSWORD=pass
        volumes:
            - ./docker/volumes/mysql:/var/lib/mysql
    mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
            - 8025:8025
